<?php if ($block->isEnabled("minicart")) : ?>
<div class="stripe-payments-express-minicart">
    <div id="payment-request-button-minicart" class="payment-request-button">&nbsp;</div>
    <script>
        require(['jquery', 'StripeIntegration_Payments/js/stripe_payments_express'], function(jQuery, stripeExpress) {
            jQuery(document).ready(function() {
                stripeExpress.initStripeExpress('#payment-request-button-minicart', '<?php echo $block->getPublishableKey(); ?>', 'minicart', <?php echo \Zend_Json::encode($block->getButtonConfig()); ?>, function (paymentRequestButton, paymentRequest, params, prButton) {
                    stripeExpress.initMiniCartWidget(paymentRequestButton, paymentRequest, params, prButton);
                });
            });
        });
    </script>
</div>
<?php endif; ?>
