<?php
/**
 * Category view template
 *
 * @var $block \Magento\Catalog\Block\Category\View
 */
?>

<?php if($block->getCurrentCategory()->getDisplayMode() != 'subcategories' || $block->getRequest()->getParam('isAjax')){ ?>
	<?php if (!$block->isContentMode() || $block->isMixedMode()): ?>
		<div id="layered-ajax-list-products">
	    <?php echo $block->getProductListHtml() ?>
	    </div>
		<script type="text/x-magento-init">
			{
				".quickview-product [data-role=quickview-button]": {
					"productQuickview": {}
				}
			}
		</script>
	<?php endif; ?>
<?php }else{ ?>
	<div id="layered-ajax-list-products">
		<?php $current_category = $block->getCurrentCategory();
		$subcategories = $current_category->getCategories($current_category->getId());
	    if($subcategories->count() > 0){ ?>
			<div class="categories-list">
			
			<?php $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
			$storeManager = $objectManager->get('Magento\Store\Model\StoreManagerInterface'); 
			$currentStore = $storeManager->getStore();
			$mediaUrl = $currentStore->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
			
			$categoryHelper = $objectManager->get('\Magento\Catalog\Helper\Category');
			?>
			
	        <?php foreach($subcategories as $subcategory){ ?>
				<?php $subcategory = $objectManager->create('Magento\Catalog\Model\Category')->load($subcategory->getId()); ?>
				<div class="col-lg-4 col-md-6 col-sm-6 category-box grouped-product franciskirk-box grid-item">
					<a href="<?php echo $categoryHelper->getCategoryUrl($subcategory); ?>" class="anchor-neutral">
						<figure>
							<div class="alp-image-holder">
								<?php if($subcategory->getImageUrl()){ ?>
									<img class="img-responsive alp-product-image" src="<?php echo $subcategory->getImageUrl(); ?>" alt="<?php echo $subcategory->getName(); ?>" />
								<?php }else{ ?>
									<img class="img-responsive alp-product-image" src="<?php echo $mediaUrl; ?>images/placeholder.png" alt="<?php echo $subcategory->getName(); ?>" />
								<?php } ?>
							</div>
							<figcaption><?php echo $subcategory->getName(); ?></figcaption>
						</figure>
					</a>
				</div>
	        <?php } ?>
			</div>
	    <?php } ?>
	</div>
	<script type="text/x-magento-init">
		{
			".quickview-product [data-role=quickview-button]": {
				"productQuickview": {}
			}
		}
	</script>
<?php } ?>
