<?php
/**
 * Cminds MultiUserAccounts manage subaccounts table template.
 *
 * @category    Cminds
 * @package     Cminds_MultiUserAccounts
 * @author      Piotr Pierzak <piotr@cminds.com>
 */
?>
<?php
/**
 * @var \Cminds\MultiUserAccounts\Block\Manage\Table $block
 */
?>
<?php $editFlag = $block->getSubbaccountEditPermission()?>
<?php $canManageSub = $block->getCanManageSubaccounts(); ?>
<?php $subaccounts = $block->getSubaccounts(); ?>

<?php if ($subaccounts && count($subaccounts)) : ?>
    <?php if (!$editFlag && !$canManageSub) {
        echo '<div class="message info empty"><span>Administrator disabled edition and creation of subaccounts</span></div>';
    }?>
    <div class="block block-search" style="float: none!important;">
        <div class="block block-content">
            <form class="form minisearch" id="search_mini_form" method="get">
                <div class="field search">
                    <label class="label" for="search" data-role="minisearch-label">
                        <span>Search</span>
                    </label>
                    <div class="control">
                        <input id="search" type="text" name="query" value="<?php if ($block->getQuery()) echo $block->getQuery(); ?>" placeholder="Search subaccounts..." class="input-text" maxlength="128">
                    </div>
                </div>
                <div class="actions">
                    <button type="submit" title="Search" class="action search">
                        <span>Search</span>
                    </button>
                </div>
            </form>
        </div>
    </div>

    <div class="table-wrapper subaccounts-manage">
        <table class="data table table-order-items subaccounts" id="subaccounts-manage-table">
            <caption class="table-caption"><?= /* @escapeNotVerified */ __('Subaccounts') ?></caption>
            <thead>
            <tr>
                <th scope="col" class="col date"><?= /* @escapeNotVerified */ __(!$block->isLoginAuth() ? 'Email' : 'Login') ?></th>
                <th scope="col" class="col shipping"><?= /* @escapeNotVerified */ __('Name') ?></th>
                <th scope="col" class="col total"><?= /* @escapeNotVerified */ __('Permission') ?></th>
                <th scope="col" class="col status"><?= /* @escapeNotVerified */ __('Status') ?></th>
                <th scope="col" class="col actions">&nbsp;</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($subaccounts as $subaccount) : ?>
                <?php
                $subaccountName = $block->getSubaccountName($subaccount);
                $permission = $block->getSubaccountPermissionDescriptionHtml($subaccount);
                $status = $block->getSubaccountStatus($subaccount);
                ?>
                <tr>
                    <td data-th="<?= $block->escapeHtml(__(!$block->isLoginAuth() ? 'Email' : 'Login')) ?>"
                        class="col email"><?= $block->escapeHtml(!$block->isLoginAuth() ? $subaccount->getEmail() : $subaccount->getLogin()) ?></td>
                    <td data-th="<?= $block->escapeHtml(__('Name')) ?>"
                        class="col name"><?= $block->escapeHtml($subaccountName) ?></td>
                    <td data-th="<?= $block->escapeHtml(__('Permission')) ?>"
                        class="col permission"><?= $block->escapeHtml($permission, ['ul', 'li']) ?></td>
                    <td data-th="<?= $block->escapeHtml(__('Status')) ?>"
                        class="col status"><?= $block->escapeHtml($status) ?></td>
                    <td data-th="<?= $block->escapeHtml(__('Actions')) ?>"
                        class="col actions">
                        <a href="<?= $block->getEditUrl($subaccount);?>"
                           class="<?= 'action edit';?>">
                            <span><?= __('Edit') ?></span>
                        </a>
                        <a href="<?= $block->getEmulateUrl($subaccount);?>"
                           class="<?= 'action edit js-invalidate-customer';?>">
                            <span><?= __('Login') ?></span>
                        </a>
                        <form action="<?= $block->getDeleteUrl($subaccount);?>"<?php if (!$canManageSub) {
                            echo 'style=display:none;';
                                      } ?>method="post">
                            <a href="#" class="<?= 'action delete';?>">
                                <span><?= __('Delete') ?></span>
                            </a>
                        </form>
                        <?php if (!$canManageSub) {?>
                        <a href="#" style="color:#d10029;">
                            <span><?= __('Delete') ?></span>
                        </a>
                        <?php }?>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
        <script type="text/javascript">
            require([ 'jquery'], function($) {
                $(function() {
                    $('#subaccounts-manage-table a.delete').bind('click', function() {
                        if (confirm('<?= __('Are you sure that you want to delete this subaccount?') ?>')) {
                            $(this).closest('form').submit();
                        }
                    });
                });
            });
        </script>
    </div>
    <?php if ($block->getPagerHtml()) : ?>
        <div class="order-products-toolbar toolbar bottom"><?= $block->getPagerHtml(); ?></div>
    <?php endif ?>
<?php else : ?>
    <div class="block block-search" style="float: none!important;">
        <div class="block block-content">
            <form class="form minisearch" id="search_mini_form" method="get">
                <div class="field search">
                    <label class="label" for="search" data-role="minisearch-label">
                        <span>Search</span>
                    </label>
                    <div class="control">
                        <input id="search" type="text" name="query" value="<?php if ($block->getQuery()) echo $block->getQuery(); ?>" placeholder="Search subaccounts..." class="input-text" maxlength="128">
                    </div>
                </div>
                <div class="actions">
                    <button type="submit" title="Search" class="action search">
                        <span>Search</span>
                    </button>
                </div>
            </form>
        </div>
    </div>
    <div class="message info empty">
        <span><?= __('There are not subaccounts to display.'); ?></span>
    </div>
<?php endif ?>

<form class="form subaccounts-manage"
      action="<?= $block->getFormActionUrl();?>"
      method="post"
      id="subaccounts-manage-add-user">
    <div class="actions">
        <button type="submit" class="action add-user primary"
                title="<?= __('Add Subaccount') ?>"<?php if (!$canManageSub) {
            echo 'disabled';
        }?>>
            <span><?= __('Add Subaccount') ?></span>
        </button>
    </div>
</form>

<script type="text/javascript">
    require([ 'jquery'], function($) {
        $(function() {
            $('.js-invalidate-customer').bind('click', function(event) {
                event.preventDefault();
                $.ajax({
                    url: $(event.target).closest('a').attr('href'),
                    type: 'post',
                    success: function () {
                        window.location = '/customer/account'
                    }
                })
            });
        });
    });
</script>
