<?php
/**
 * Copyright © 2015 RokanThemes.com. All rights reserved.

 * @author RokanThemes Team <contact@rokanthemes.com>
 */
?>
<?php
/**
 * Blog post list item template
 *
 * @var $block \Rokanthemes\Blog\Block\Post\AbstractPost
 */
?>
<?php
    $_post = $this->getPost();
    $_postUrl = $_post->getPostUrl();
    $_postName = $block->escapeHtml($_post->getTitle(), null, true);
?>
<li class="col-sm-4 post-holder post-holder-<?php echo $_post->getId() ?>">
	<div class="post-images">
		<a href="<?php echo $_post->getPostUrl() ?>">
			<img src="<?php echo $this->getMediaFolder().$_post->getThumbnailimage() ?>"/>
		</a>	
	</div>
	<div class="post-content">
		
		<?php echo $this->getInfoHtml() ?>
		<div class="post-title-holder clearfix">
			<h2 class="post-title">
				<a class="post-item-link"
				   href="<?php echo $_postUrl ?>">
					<?php echo $_postName; ?>
				</a>
			</h2> 
		</div> 
		<div class="post-description clearfix">
			<?php echo $block->getShortContent() ?>
			
		</div>
		<!--<a class="post-read-more" href="<?php echo $_postUrl ?>" title="<?php echo $_postName ?>"
			   >
		   <?php echo __('Continus Reading &#187;') ?>
		</a>-->
	</div> 
</li>