<?php
$specificInfo = $block->getSpecificInformation();
$paymentTitle = $block->getMethod()->getConfigData('title', $block->getInfo()->getOrder()->getStoreId());
?>
<p><?= $block->escapeHtml($paymentTitle) ?></p>

<p><?php echo __("Your order is pending! To complete the order, please transfer <b>%1</b> to the following bank account:", $block->getFormattedDueAmount()); ?>

<table class="data-table admin__table-secondary">
<?php foreach ($specificInfo as $label => $value) : ?>
    <tr>
        <th><?= $block->escapeHtml($label) ?>:</th>
        <td>
            <?= /* @noEscape */ nl2br($block->escapeHtml(implode("\n", $block->getValueAsArray($value, true)))) ?>
        </td>
    </tr>
<?php endforeach; ?>
</table>

<?= $block->getChildHtml() ?>
