<?php
// @codingStandardsIgnoreFile
/**
 * @var $block \StripeIntegration\Payments\Block\Sepa
 */
$code = \StripeIntegration\Payments\Model\Method\Sepa::METHOD_CODE;
$iban = $block->getInfoData('iban');
$company = $block->getCompany();
?>

<fieldset class="stripe-payments indent-target items payment-method <?php echo $code; ?>" id="payment_form_<?php echo $code; ?>" style="display: none">
    <div class="fieldset">
        <div class="field _required">
            <label class="label" for="<?php echo $code; ?>_iban">
                <span><?php echo $block->escapeHtml(__('IBAN')); ?></span>
            </label>
            <div class="control">
                <input type="text" id="<?php echo $code; ?>_iban"
                        name="payment[iban]"
                       title="<?php echo $block->escapeHtml(__('IBAN')); ?>" class="text"
                       value="<?php /* @noEscape */ echo $block->getInfoData('iban'); ?>" />
            </div>
            <div class="control payment-method-note mandate">
                <?php echo $block->escapeHtml(__('By providing your IBAN and confirming this payment, you authorise (A) %1 and Stripe, our payment service provider, to send instructions to your bank to debit your account and (B) your bank to debit your account in accordance with the instructions from %1 and Stripe. As part of your rights, you are entitled to a refund from your bank under the terms and conditions of your agreement with your bank. A refund must be claimed within 8 weeks starting from the date on which your account was debited.', $company)); ?>
            </div>
        </div>
    </div>
</fieldset>
