<ul class="top-link">

	<?php if($this->helper('Rokanthemes\Themeoption\Helper\Data')->isLoggedIn()): ?>

	<li><a href="<?php echo $this->helper('Rokanthemes\Themeoption\Helper\Data')->getBaseUrl('customer/account/logout');?>"><?php echo __('Logout');?></a></li>	

	<li><a href="<?php echo $this->helper('Rokanthemes\Themeoption\Helper\Data')->getBaseUrl('customer/account/'); ?>"><?php echo __('My account') ?></a></li>

	<?php else: ?>

	<li><a href="<?php echo $this->helper('Rokanthemes\Themeoption\Helper\Data')->getBaseUrl('customer/account/login/'); ?>"><?php echo __('My account') ?></a></li>

	<?php endif ?>

	<!-- <li><a href="<?php //echo $this->helper('Rokanthemes\Themeoption\Helper\Data')->getBaseUrl('wishlist/index/index/'); ?>"><?php //echo __('Wish list') ?></a></li> -->

	<li><a href="<?php echo $this->helper('Rokanthemes\Themeoption\Helper\Data')->getBaseUrl('checkout/'); ?>"><?php echo __('My Cart') ?></a></li>

	<li><a href="<?php echo $this->helper('Rokanthemes\Themeoption\Helper\Data')->getBaseUrl('checkout/cart/'); ?>"><?php echo __('Checkout') ?></a></li>

</ul>