<?php 
	$enable = $block->getConfig('enabled');
	if($enable < 1) return ; 
	$items = $block->getConfig('items');
	$speed = $block->getConfig('speed');
	$qty = $block->getConfig('qty');
	$showCart = $block->getConfig('addtocart');
	$showWishlist = $block->getConfig('wishlist');
	$showCompare = $block->getConfig('compare');
	$show_navigation = $block->getConfig('navigation');
	$show_pagination = $block->getConfig('pagination');
	$auto = $block->getConfig('auto');
	$rows = $block->getSlideRow();
	$slide_limit = $block->getSlideLimit();
	$title = $block->getTitle(); 
	$identify = trim($block->getIdentify()); 
	$categoryIds = $block->getCategoryIds();
	$categoryIds = explode(',', $categoryIds);

?>

<div class="categorytab-container">
<div class="container">
<header class='group-title1'><?php 	echo '<h2>'.$title.'</h2>'; ?></header>
  <ul class="tabs tabs<?php echo '-'.$identify;?>"> 
   <?php 
	$k = 0;
	foreach($categoryIds as $cate_id) {
		$cate_model =  $block->getCategory($cate_id);
		$cateName = $cate_model->load($cate_id)->getName();
		//echo "<pre>"; print_r($cate_model->getData()); die; 
		if($cateName) {
   ?>
			<li class="<?php if($k==0){ echo "active"; }?>" rel="tab<?php echo $cate_id.'-'.$identify;?>"><?php  echo $cateName; ?></li>
	<?php }  $k++; } ?>
    </ul>
     <?php 
		
		$imageBlock =  $block->getLayout()->createBlock('Magento\Catalog\Block\Product\Image');
		$image = 'new_products_content_widget_grid';
		$type = 'widget-new-grid';
		$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::DEFAULT_VIEW;
		$showWishlist = true;
		$showCompare = true;
		$showCart = true;
	?>
	<div class="tab_container"> 
		<?php foreach($categoryIds as $cate_id) { ?>
		<div id="tab<?php echo $cate_id.'-'.$identify;?>" class="tab_content_<?php echo $identify; ?>"> 
		<div class="owl-container">		
			<div class="category_tab_slider owl-carousel">
				<?php 
				$newItems =  $block -> getProductCate($cate_id)->getItems(); 
				$i=0;
				foreach($newItems as $_item) { 
					$productImage = $block->getImage($_item, $image);
				?>
				<?php if($i++%$rows==0) { ?> <div class="product_row"> <?php } ?>
					<div class="item">
						<div class="item-inner">
							<div class="image-container">
								<a href="<?php echo $block->getProductUrl($_item) ?>" class="product-item-photo">
									<?php echo $productImage->toHtml() ?>
								</a>
								<div class="actions">
									<?php if ($showCart): ?>
										<div class="actions-primary">
											<?php if ($_item->isSaleable()): ?>
												<?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)): ?>
													<button class="action tocart"
															data-mage-init='{"redirectUrl":{"url":"<?php echo $block->getAddToCartUrl($_item) ?>"}}'
															type="button" title="<?php echo __('Add to Cart') ?>">
														<span><?php echo __('Add to Cart') ?></span>
													</button>
												<?php else: ?>
													<?php
														$postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
														$postData = $postDataHelper->getPostData($block->getAddToCartUrl($_item), ['product' => $_item->getEntityId()])
													?>
													<button class="action tocart"
															data-post='<?php echo $postData; ?>'
															type="button" title="<?php echo __('Add to Cart') ?>">
														<span><?php echo __('Add to Cart') ?></span>
													</button>
												<?php endif; ?>
											<?php else: ?>
												<?php if ($_item->getIsSalable()): ?>
													<div class="stock available"><span><?php echo __('In stock') ?></span></div>
												<?php else: ?>
													<div class="stock unavailable"><span><?php echo __('Out of stock') ?></span></div>
												<?php endif; ?>
											<?php endif; ?>
										</div>
									<?php endif; ?>
									<?php if ($showWishlist || $showCompare): ?>
										<div class="actions-secondary add-to-links" data-role="add-to-links">
											<?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && $showWishlist): ?>
												<a href="#"
												   data-post='<?php echo $block->getAddToWishlistParams($_item); ?>'
												   class="action towishlist" data-action="add-to-wishlist"
												   title="<?php echo __('Add to Wishlist') ?>">
													<span><?php echo __('Add to Wishlist') ?></span>
												</a>
											<?php endif; ?>
											<?php if ($block->getAddToCompareUrl() && $showCompare): ?>
												<?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');?>
												<a href="#" class="action tocompare"
												   data-post='<?php echo $compareHelper->getPostDataParams($_item);?>'
												   title="<?php echo __('Add to Compare') ?>">
													<span><?php echo __('Add to Compare') ?></span>
												</a>
											<?php endif; ?>
										</div>
									<?php endif; ?>
								</div>
							</div>
							<div class="des">
								<div class="product-name">
									<strong class="product-item-name">
										<a title="<?php echo $block->escapeHtml($_item->getName()) ?>"
										   href="<?php echo $block->getProductUrl($_item) ?>"
										   class="product-item-link">
											<?php echo $block->escapeHtml($_item->getName()) ?>
										</a>
									</strong>
								</div>
								<?php /* @escapeNotVerified */ echo $this->helper('Rokanthemes\Themeoption\Helper\Data')->getPriceDisplayCustom($block->getProductPrice($_item)) ?>
								 
								<?php if ($templateType): ?>
									<?php echo $block->getReviewsSummaryHtml($_item, $templateType,true); ?>
								<?php endif; ?>
								
							</div>
						</div>
					</div>
						<?php if($i%$rows==0 || $i == count($newItems)) { ?> </div> <?php }?>
				<?php 
				}
				?>
			</div>
		</div>	
			
		 </div><!-- #tab1 -->
		 <?php }?>

		 
	 </div> <!-- .tab_container --> 
</div>
</div>
<script type="text/javascript">
require(['jquery', 'mage/mage', 'rokanthemes/owl'], function ($) {
	'use strict';
	$( document ).ready(function() {
		$(".tab_content_<?php echo $identify; ?>").hide();
		$(".tab_content_<?php echo $identify; ?>:first").show(); 
	});
});
 

</script> 
