<?php
/**
 * Copyright © 2016 TuanHatay. All rights reserved.
 */

?>
<?php
/**
 * Top menu for store
 *
 * @see \Rokanthemes\CustomMenu\Block\Topmenu
 */
?>
<?php
    $_helper = $this->helper('Rokanthemes\CustomMenu\Helper\Data');
    $_config = $_helper->getConfig('custommenu');
    $columnsLimit = 0;
    if($_config['general']['enable']) {
?>
<?php $_menu = $block->getCustomMenuHtml(); ?>

<nav class="navigation custommenu side-custommenu" role="navigation">
    <ul>
        <?php echo $_menu; ?>
    </ul>
</nav>

<script type="text/javascript">
    require([
        'jquery',
        'rokanthemes/custommenu'
    ], function ($) {
        $(".custommenu").CustomMenu();
    });
</script>
<?php
    }
?>