<ol class="items">
    <?php foreach ($filterItems as $filterItem): ?>
        <?php
        $filter = $filterItem->getFilter();
        $attributeModel = $filter->getData('attribute_model');
        $inputName = $filter->getRequestVar();
        $requestValue = $block->getRequest()->getParam($inputName);
        $requestArray = $requestValue ? explode(',', $requestValue) : [];
        $url = in_array($filterItem->getValue(), $requestArray) ? $filterItem->getRemoveUrl() : $filterItem->getUrl();
		if($inputName == 'cat'){
			$ex_url = explode("cat=", $url);
			if(isset($ex_url[1])){
				$ex2_url = explode("%2C",$ex_url[1]);
				if(isset($ex2_url[1])){
					$url = $ex_url[0].'cat='.$ex2_url[1];
				}
			}
		}
        ?>
        <li class="item">
            <?php if($this->helper('Rokanthemes\LayeredAjax\Helper\Data')->isEnabledPriceRangeSliders() && $attributeModel && $attributeModel->getFrontendInput() == 'price'): ?>
                <?php
                    $productCollection = $filter->getLayer()->getProductCollection();
					$min = $productCollection->getMinPrice();
                    $max = $productCollection->getMaxPrice();

                    list($from, $to) = $requestValue ? explode('-', $requestValue) : [$min, $max];
                ?>
                <div id="layered_ajax_price_attribute">
                    <div id="layered_ajax_price_text"></div>
					<div id="layered_ajax_price_slider"></div>
                </div>
                <script type="text/x-magento-init">
                    {
                        "#layered_ajax_price_attribute": {
                            "Rokanthemes_LayeredAjax/js/price/layeredajaxslider": {
                                "selectedFrom": <?php echo $from ?>,
                                "selectedTo": <?php echo $to ?>,
                                "minValue": <?php echo $min ?>,
                                "maxValue": <?php echo $max ?>,
                                "priceFormat": <?php echo $this->helper('Magento\Tax\Helper\Data')->getPriceFormat($block->getStore()); ?>,
                                "ajaxUrl": <?php echo $this->helper('Magento\Framework\Json\Helper\Data')->jsonEncode($filterItem->getUrl()) ?>
                            }
                        }
                    }
                </script>
                <?php break; ?>
            <?php else: ?>
				<?php if ($filterItem->getCount() > 0): ?>
                    <a <?php echo in_array($filterItem->getValue(), $requestArray) ? 'class="active"' : ''  ?> href="<?php echo $block->escapeUrl($url) ?>">
                        <?php if($attributeModel && $attributeModel->getFrontendInput() == 'multiselect'): ?>
                            <input type="checkbox" <?php echo in_array($filterItem->getValue(), $requestArray) ? 'checked="checked"' : ''  ?> />
                        <?php endif; ?>
						<?php echo $filterItem->getLabel() ?>
                        <?php if ($this->helper('\Magento\Catalog\Helper\Data')->shouldDisplayProductCountOnLayer()): ?>
                            <span class="count"><?php echo $filterItem->getCount()?><span class="filter-count-label">
								<?php if ($filterItem->getCount() == 1):?> <?php echo __('item')?><?php else:?> <?php echo __('items') ?><?php endif;?></span></span>
                        <?php endif; ?>
					</a>
                <?php else:?>
                    <?php if($attributeModel && $attributeModel->getFrontendInput() == 'multiselect'): ?>
                        <input type="checkbox" disabled="disabled" />
                    <?php endif; ?>
                    <?php echo $filterItem->getLabel() ?>
                    <?php if ($this->helper('\Magento\Catalog\Helper\Data')->shouldDisplayProductCountOnLayer()): ?>
                        <span class="count"><?php echo $filterItem->getCount()?><span class="filter-count-label">
							<?php if ($filterItem->getCount() == 1):?><?php echo __('item')?><?php else:?><?php echo __('items') ?><?php endif;?></span></span>
                    <?php endif; ?>
                <?php endif; ?>
            <?php endif; ?>
        </li>
    <?php endforeach ?>
</ol>