<?php if ($block->canShowBlock()): ?>
    <div class="block filter" id="layered-ajax-filter-block" data-mage-init='{"collapsible":{"openedState": "active", "collapsible": true, "active": true, "collateral": { "openedState": "filter-active", "element": "body" } }}'>
		<div class="block-content filter-content sidebar-shop sidebar-left">
            <?php if ($block->getLayer()->getState()->getFilters()): ?>
				<div class="widget">
					<?php echo $block->getChildHtml('state') ?>
					<div class="block-actions filter-actions">
						<a href="<?php /* @escapeNotVerified */ echo $block->getClearUrl() ?>" class="action clear filter-clear"><span><?php /* @escapeNotVerified */ echo __('Clear All') ?></span></a>
					</div>
				</div>
            <?php endif; ?>
            <?php $wrapOptions = false; $activeKey = 0; $activeArray = []; ?>
            <?php foreach ($block->getFilters() as $key => $filter): ?>
                <?php if ($filter->getItemsCount()): ?>
                    <?php if (!$wrapOptions): ?>
                       <div class="filter-options widget widget-filter" id="narrow-by-list" data-role="content">
                    <?php  $wrapOptions = true; endif; ?>
                    <div data-role="collapsible" class="filter-options-item">
                        <div data-role="title" class="filter-options-title"><?php /* @escapeNotVerified */ echo __($filter->getName()) ?></div>
                        <div data-role="content" class="filter-options-content"><?php /* @escapeNotVerified */ echo $block->getChildBlock('renderer')->render($filter); ?></div>
                    </div>
                    <?php
						if($this->helper('Rokanthemes\LayeredAjax\Helper\Data')->isOpenAllTab()){
							$activeArray[] = $activeKey;
						}
                        $activeKey++;
                    ?>
                <?php endif; ?>
            <?php endforeach; ?>
            <?php if ($wrapOptions): ?>
                </div>
                <div class="banner_left_2">
                    <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('banner_left2_home1')->toHtml();?>
                </div>
				<script type="text/x-magento-init">
					{
						"#narrow-by-list": {
							"accordion": {
								"openedState": "active",
								"collapsible": true,
								"active": <?php echo $this->helper('Magento\Framework\Json\Helper\Data')->jsonEncode($activeArray); ?>,
								"multipleCollapsible": true
							},
							"Rokanthemes_LayeredAjax/js/layeredajax": {}
						}
					}
				</script>
            <?php endif; ?>
        </div>
		<div id="layered_ajax_overlay" class="layered_ajax_overlay">
			<div><img src="<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('images/loader-1.gif'); ?>" alt="<?php echo __('Loading') ?>"></div>
		</div>
    </div>
<?php endif; ?>