<?php

/**

 * Copyright © 2015 Magento. All rights reserved.

 * See COPYING.txt for license details.

 */

use Magento\Framework\App\Action\Action;



// @codingStandardsIgnoreFile



?>

<?php

/**

 * Product list template

 *

 * @var $block \Magento\Catalog\Block\Product\ListProduct

 */

?>

<?php

$_productCollection = $block->getLoadedProductCollection();

$_helper = $this->helper('Magento\Catalog\Helper\Output');

$isEnableQuickView = $this->helper('Rokanthemes\QuickView\Helper\Data')->isEnable();

?>

<?php if (!$_productCollection->count()): ?>

    <div class="message info empty"><div><?php /* @escapeNotVerified */ echo __('We can\'t find products matching the selection.') ?></div></div>

<?php else: ?>

    <?php echo $block->getToolbarHtml() ?>

    <?php echo $block->getAdditionalHtml() ?>

    <?php

    if ($block->getMode() == 'grid') {

        $viewMode = 'grid';

        $image = 'category_page_grid';

        $showDescription = false;

        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;

    } else {

        $viewMode = 'list';

        $image = 'category_page_list';

        $showDescription = true;

        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;

    }

   /*Grid*/

	if($viewMode == "grid"):

		/**

		 * Position for actions regarding image size changing in vde if needed

		 */

		$pos = $block->getPositioned();

	?>

    <div class="products wrapper <?php /* @escapeNotVerified */ echo $viewMode; ?> products-<?php /* @escapeNotVerified */ echo $viewMode; ?>">

        <?php $iterator = 1; ?>

        <ol class="product-grid row">

            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>

            <?php foreach ($_productCollection as $_product): ?>

                <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<li class="item-inner product-item-toki col-sm-4 col-xs-4">' : '</li><li class="item-inner product-item-toki col-sm-4 col-xs-4">' ?>

                <div class="product-info product-item-info">

					<div class="product-list-item product-item-details">

	                    <?php

	                    $productImage = $block->getImage($_product, $image);

	                    if ($pos != null) {

	                        $position = ' style="left:' . $productImage->getWidth() . 'px;'

	                            . 'top:' . $productImage->getHeight() . 'px;"';

	                    }

	                    ?>

	                     

						<div class="product-photo">

							<a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">

								<?php $productImageThumb = $block->getImage($_product, 'category_page_grid-1');?>

								<span class="image0 image-switch">

									<?php echo $productImage->toHtml(); ?>

								</span>

								<span class="image1 image-switch">

									<?php echo $productImageThumb->toHtml(); ?>

								</span>

							</a>

						  	<div class="addto-links-icons visible-onhover">

								<div class="action-inner">	

									<ul class="add-to-links">

										<?php if ($isEnableQuickView): ?>

										<li>

											<div class="quickview-product">

												<a href="javascript:void(0)" data-role="quickview-button" data-id="<?php echo $_product->getId(); ?>" data-href="<?php echo $block->getUrl('quickview/product/quickview/id/' . $_product->getId()) ?>" title="<?php echo $block->escapeHtml(__('Quick view')); ?>" class="ajax diamond tooltip-hover" data-placement="top" data-original-title="<?php echo ('Quick view') ?>"><i class="fa fa-compress"></i></a>

										    </div>

										</li>

										<?php endif; ?>

					

										<?php

										$compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');

										?>

										<li><a href="#"

										   class="action button tocompare"

										   title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"

										   aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"

										   data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_product); ?>'

										   role="button">

											<i class="fa fa-sliders"></i>

											</a>

										</li>



										<li>

											<a href="#"

											   class="action button towishlist"

											   title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"

											   aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"

											   data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_product); ?>'

											   data-action="add-to-wishlist"

											   role="button">

												<i class="fa fa-heart-o"></i>

											</a>

										</li>

									</ul>

								</div>

							</div>

							<?php if ( $_product->getFinalPrice() < $_product->getPrice() ): ?>

								<span class="onsale">

									<span class="sale-bg"></span>

									<span class="sale-text"><?php echo __('Sale') ?></span>

								</span>

							<?php endif; ?>

							<?php $todayDate = time(); 

								$timeStartNew = strtotime($_product->getData('news_from_date'));

								$timeEndNew = strtotime($_product->getData('news_to_date')); ?>

							<?php if ( $timeEndNew >= $todayDate && $timeStartNew <= $todayDate): ?>

								<span class="newlabel">

									<span><?php echo __('New') ?></span>

								</span>

							<?php endif; ?>

						</div>

	                    <div class="product-info-bottom">

							<?php

								$_productNameStripped = $block->stripTags($_product->getName(), null, true);

							?>

							<h3 class="product-name">

								<a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>">

									<?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>

								</a>

							</h3>

							<?php /* @escapeNotVerified */ echo $block->getProductPrice($_product) ?>

							<?php 
							$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
							$stockRegistry = $objectManager->get('\Magento\CatalogInventory\Api\StockRegistryInterface');
							$stockItem = $stockRegistry->getStockItem($_product->getId());
							$product = $objectManager->create('Magento\Catalog\Model\Product')->load($_product->getId());
							//if($product->getData('price_structure') && !$stockItem->getManageStock()){
								if($product->getData('price_unit') != ''){ ?>
									<div class="price_unit"><?php echo 'Per '.$product->getData('price_unit'); ?></div>
								<?php }
							//}else{
								if($product->getData('pack_qty') != ''){ ?>
									<?php
										$eavConfig = $objectManager->get('\Magento\Eav\Model\Config');
										$pack_qty = $eavConfig->getAttribute('catalog_product', 'pack_qty');
									?>
									<div class="pack_qty"><?php echo $pack_qty->getData('frontend_label').': '.$product->getData('pack_qty'); ?></div>
								<?php }
							//} ?>

							

							<div class="product-details-fixed">

								<?php echo $block->getProductDetailsHtml($_product); ?>

							</div>

							<div class="actions-primary"<?php echo strpos($pos, $viewMode . '-primary') ? $position : ''; ?>>

								<?php if ($_product->isSaleable()): ?>

									<?php $postParams = $block->getAddToCartPostParams($_product); ?>

									<form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post">

										<input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">

										<input type="hidden" name="<?php /* @escapeNotVerified */ echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */ echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">

										<?php echo $block->getBlockHtml('formkey')?>

										<button type="submit"

												title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"

												class="btn btn-add-to-cart">

											<i class="icon icon_bag_alt"></i><span><?php echo $block->escapeHtml(__('Add to Cart')); ?></span>

										</button>

									</form>

								<?php else: ?>

									<?php if ($_product->getIsSalable()): ?>

										<div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>

									<?php else: ?>

										<div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>

									<?php endif; ?>

								<?php endif; ?>

							</div>

	                    </div>

	                </div>

            	</div>

                <?php echo($iterator == count($_productCollection)+1) ? '</li>' : '' ?>

            <?php endforeach; ?>

        </ol>

    </div>

    <?php echo $block->getToolbarHtml() ?>

    <?php if (!$block->isRedirectToCartEnabled()) : ?>

        <script type="text/x-magento-init">

        {

            "[data-role=tocart-form], .form.map.checkout": {

                "catalogAddToCart": {}

            }

        }

        </script>

    <?php endif; ?>

	<?php

		/*List*/

		else:

			/**

			 * Position for actions regarding image size changing in vde if needed

			 */

			$pos = $block->getPositioned();

	?>

		<div class="products wrapper <?php /* @escapeNotVerified */ echo $viewMode; ?> products-<?php /* @escapeNotVerified */ echo $viewMode; ?>">

			<?php $iterator = 1; ?>

			<ol class="product-list">

				<?php /** @var $_product \Magento\Catalog\Model\Product */ ?>

				<?php foreach ($_productCollection as $_product): ?>

					<?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<li class="item product product-item product-item-toki">' : '</li><li class="item product product-item product-item-toki">' ?>

					<div class="row">

						<?php

						$productImage = $block->getImage($_product, $image);

						if ($pos != null) {

							$position = ' style="left:' . $productImage->getWidth() . 'px;'

								. 'top:' . $productImage->getHeight() . 'px;"';

						}

						?>

						 

						<div class="col-sm-6 col-md-4 col-xs-12">

							<div class="product-photo">

								<a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" tabindex="-1">

									<?php echo $productImage->toHtml(); ?>

								</a>

								<?php if ( $_product->getFinalPrice() < $_product->getPrice() ): ?>

									<span class="onsale">

										<span class="sale-bg"></span>

										<span class="sale-text"><?php echo __('Sale') ?></span>

									</span>

								<?php endif; ?>

								<?php $todayDate = time(); 

									$timeStartNew = strtotime($_product->getData('news_from_date'));

									$timeEndNew = strtotime($_product->getData('news_to_date')); ?>

								<?php if ( $timeEndNew >= $todayDate && $timeStartNew <= $todayDate): ?>

									<span class="newlabel">

										<span><?php echo __('New') ?></span>

									</span>

								<?php endif; ?>

							</div>

						</div>

						<div class="product details product-item-details col-md-8 col-sm-6 col-xs-12">

							<div class="product-info product-info-bottom" data-container="product-list">

								<?php

									$_productNameStripped = $block->stripTags($_product->getName(), null, true);

								?>

								<h3 class="product-name">

									<a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>">

										<?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>

									</a>

								</h3>

								<div class="product-ratting">

									<?php echo $block->getReviewsSummaryHtml($_product, $templateType); ?>

								</div>

								<?php /* @escapeNotVerified */ echo $block->getProductPrice($_product) ?>
								
								<?php 
								$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
								$stockRegistry = $objectManager->get('\Magento\CatalogInventory\Api\StockRegistryInterface');
								$stockItem = $stockRegistry->getStockItem($_product->getId());
								$product = $objectManager->create('Magento\Catalog\Model\Product')->load($_product->getId());
								//if($product->getData('price_structure') && !$stockItem->getManageStock()){
									if($product->getData('price_unit') != ''){ ?>
										<div class="price_unit"><?php echo 'Per '.$product->getData('price_unit'); ?></div>
									<?php }
								//}else{
									if($product->getData('pack_qty') != ''){ ?>
										<?php
											$eavConfig = $objectManager->get('\Magento\Eav\Model\Config');
											$pack_qty = $eavConfig->getAttribute('catalog_product', 'pack_qty');
										?>
										<div class="pack_qty"><?php echo $pack_qty->getData('frontend_label').': '.$product->getData('pack_qty'); ?></div>
									<?php }
								//} ?>

								<?php if ($showDescription):?>

	                                <div class="product description product-item-description">

	                                    <?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>

	                                </div>

	                            <?php endif; ?>

	                            <div class="product-details-fixed">

									<?php echo $block->getProductDetailsHtml($_product); ?>

	                            </div>

								<div class="addto-links-icons visible-onhover">

									<div class="action-inner product-item-actions"<?php echo strpos($pos, $viewMode . '-actions') ? $position : ''; ?>>

										<div class="actions-primary"<?php echo strpos($pos, $viewMode . '-primary') ? $position : ''; ?>>

											<?php if ($_product->isSaleable()): ?>

												<?php $postParams = $block->getAddToCartPostParams($_product); ?>

												<form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post">

													<input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">

													<input type="hidden" name="<?php /* @escapeNotVerified */ echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */ echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">

													<?php echo $block->getBlockHtml('formkey')?>

													<button type="submit"

	                                                    title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"

	                                                    class="action tocart primary">

														<span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>

													</button>

												</form>

											<?php else: ?>

												<?php if ($_product->getIsSalable()): ?>

													<div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>

												<?php else: ?>

													<div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>

												<?php endif; ?>

											<?php endif; ?>

										</div>

										<div data-role="add-to-links" class="actions-secondary"<?php echo strpos($pos, $viewMode . '-secondary') ? $position : ''; ?>>

											<?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()): ?>

												<a href="#"

												   class="action towishlist"

												   title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"

												   aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"

												   data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_product); ?>'

												   data-action="add-to-wishlist"

												   role="button">

													<i class="fa fa-heart-o"></i>

												</a>

											<?php endif; ?>

											<?php

											$compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');

											?>

											<a href="#"

											   class="action tocompare"

											   title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"

											   aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"

											   data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_product); ?>'

											   role="button">

												<i class="fa fa-sliders"></i>

											</a>

										</div>

									</div>

									

								</div>

							</div>

						</div>

					</div>

					<?php echo($iterator == count($_productCollection)+1) ? '</li>' : '' ?>

				<?php endforeach; ?>

			</ol>

		</div>

		<?php echo $block->getToolbarHtml() ?>

		<?php if (!$block->isRedirectToCartEnabled()) : ?>

			<script type="text/x-magento-init">

			{

				"[data-role=tocart-form], .form.map.checkout": {

					"catalogAddToCart": {}

				}

			}

			</script>

		<?php endif; ?>	

    <?php endif; ?>	

<?php endif; ?>