<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/* @var $block \Magento\Catalog\Block\Product\AbstractProduct */
?>

<?php
$blockOwlClass = '';
$isEnableQuickView = $this->helper('Rokanthemes\QuickView\Helper\Data')->isEnable();
switch ($type = $block->getType()) {

    case 'related-rule':
        if ($exist = $block->hasItems()) {
            $type = 'related';
            $class = $type;

            $image = 'related_products_list';
            $title = __('Related Products');
            $items = $block->getAllItems();
            $limit = $block->getPositionLimit();
            $shuffle = (int) $block->isShuffled();
            $canItemsAddToCart = $block->canItemsAddToCart();

            $showWishlist = true;
            $showCompare = true;
            $showCart = false;
            $templateType = null;
            $description = false;
			$blockOwlClass = '.products-related .product-items';
        }
    break;

    case 'related':
        /** @var \Magento\Catalog\Block\Product\ProductList\Related $block */
        if ($exist = $block->getItems()->getSize()) {
            $type = 'related';
            $class = $type;

            $image = 'related_products_list';
            $title = __('Related Products');
            $items = $block->getItems();
            $limit = 0;
            $shuffle = 0;
            $canItemsAddToCart = $block->canItemsAddToCart();

            $showWishlist = true;
            $showCompare = true;
            $showCart = true;
            $templateType = null;
            $description = false;
			$blockOwlClass = '.products-related .product-items';
        }
    break;

    case 'upsell-rule':
        if ($exist = $block->hasItems()) {
            $type = 'upsell';
            $class = $type;

            $image = 'upsell_products_list';
            //$title = __('Upsell Products');
            $title = __('Say Premium Products');
            $items = $block->getAllItems();
            $limit = $block->getPositionLimit();
            $shuffle = (int) $block->isShuffled();

            $showWishlist = true;
            $showCompare = true;
            $showCart = true;
            $templateType = null;
            $description = false;
            $canItemsAddToCart = false;
			$blockOwlClass = '.products-upsell .product-items';
        }
    break;

    case 'upsell':
        /** @var \Magento\Catalog\Block\Product\ProductList\Upsell $block */
        if ($exist = count($block->getItemCollection()->getItems())) {
            $type = 'upsell';
            $class = $type;

            $image = 'upsell_products_list';
            //$title = __('Upsell Products');
            $title = __('Say Premium Products');
            $items = $block->getItemCollection()->getItems();
            $limit = $block->getItemLimit('upsell');
            $shuffle = 0;

            $showWishlist = true;
            $showCompare = true;
            $showCart = true;
            $templateType = null;
            $description = false;
            $canItemsAddToCart = false;
			$blockOwlClass = '.products-upsell .product-items';
        }
    break;

    case 'crosssell-rule':
        /** @var \Magento\Catalog\Block\Product\ProductList\Crosssell $block */
        if ($exist = $block->hasItems()) {
            $type = 'crosssell';
            $class = $type;

            $image = 'cart_cross_sell_products';
            //$title = __('More Choices:');
            $title = __('Frequently Bought Products With');
            $items = $block->getItemCollection();

            $showWishlist = true;
            $showCompare = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
            $canItemsAddToCart = false;
			$blockOwlClass = '.products-crosssell .product-items';
        }
    break;

    case 'crosssell':
        /** @var \Magento\Catalog\Block\Product\ProductList\Crosssell $block */
        if ($exist = $block->getItemCount()) {
            $type = 'crosssell';
            $class = $type;

            $image = 'cart_cross_sell_products';
            //$title = __('More Choices:');
            $title = __('Frequently Bought Products With');
            $items = $block->getItems();

            $showWishlist = true;
            $showCompare = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
            $canItemsAddToCart = false;
			$blockOwlClass = '.products-crosssell .product-items';
        }
    break;

    case 'new':
        if ($exist = $block->getProductCollection()) {
            $type = 'new';
            $mode = 'grid';
            $type = $type . ' ' . $mode;

            $class = 'widget' . ' ' . $type;

            $image = 'new_products_content_widget_grid';
            $title = __('New Products');
            $items = $exist;

            $showWishlist = true;
            $showCompare = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = ($mode == 'list') ? true : false;
            $canItemsAddToCart = false;
			$blockOwlClass = '.products-new .product-items';
        }
    break;

    case 'other':
    break;
}
?>

<?php if ($exist):?>

    <?php if ($type == 'related' || $type == 'upsell'): ?>
        <?php if ($type == 'related'): ?>
            <div class="block <?php /* @escapeNotVerified */ echo $class; ?>" data-mage-init='{"relatedProducts":{"relatedCheckbox":".related.checkbox"}}' data-limit="<?php /* @escapeNotVerified */ echo $limit; ?>" data-shuffle="<?php /* @escapeNotVerified */ echo $shuffle; ?>">
        <?php else: ?>
            <div class="block <?php /* @escapeNotVerified */ echo $class; ?>" data-mage-init='{"upsellProducts":{}}' data-limit="<?php /* @escapeNotVerified */ echo $limit; ?>" data-shuffle="<?php /* @escapeNotVerified */ echo $shuffle; ?>">
        <?php endif; ?>
    <?php else: ?>
        <div class="block <?php /* @escapeNotVerified */ echo $class; ?>">
    <?php endif; ?>
    <div class="rokan-product-heading rokan-relate-heading">
		<h2><span><?php echo $title; ?></span></h2>
	</div>
    <div class="block-content content" aria-labelledby="block-<?php /* @escapeNotVerified */ echo $class?>-heading">
       
        <div class="products wrapper products-<?php /* @escapeNotVerified */ echo $type; ?>">
			<div class="row">
            <ol class="products list items product-items">
                <?php $iterator = 1; ?>
                <?php foreach ($items as $_item): ?>
                <?php $available = ''; ?>
                <?php if (!$_item->isComposite() && $_item->isSaleable() && $type == 'related'): ?>
                    <?php if (!$_item->getRequiredOptions()): ?>
                        <?php $available = 'related-available'; ?>
                    <?php endif; ?>
                <?php endif; ?>
                <?php if ($type == 'related' || $type == 'upsell'): ?>
                    <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<li class="item product" style="display: none;">' : '</li><li class="item product" style="display: none;">' ?>
                <?php else: ?>
                    <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<li class="item product">' : '</li><li class="item product">' ?>
                <?php endif; ?>
                <div class="product-item <?php /* @escapeNotVerified */ echo $available; ?>">
                    <?php
                        $productImage = $block->getImage($_item, $image);
                    ?>
					<div class="product-photo">
                        <?php /* @escapeNotVerified */ echo '<!-- ' . $image . '-->' ?>
						<a href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>" class="product photo product-item-photo">
							<?php //echo $block->getImage($_item, $image)->toHtml(); ?>
                            <?php $productImageThumb = $block->getImage($_item, 'category_page_grid-1');?>
                            <span class="image0 image-switch">
                                <?php echo $productImage->toHtml(); ?>
                            </span>
                            <span class="image1 image-switch">
                                <?php echo $productImageThumb->toHtml(); ?>
                            </span>
						</a>
                        <div class="addto-links-icons visible-onhover pull-right">
                            <div class="action-inner">
                                <?php if ($showWishlist || $showCompare ): ?>
                                <ul class="add-to-links">
                                    <?php if ($isEnableQuickView): ?>
                                    <li>
                                        <div class="quickview-product">
                                            <a href="javascript:void(0)" data-role="quickview-button" data-id="<?php echo $_item->getId(); ?>" data-href="<?php echo $block->getUrl('quickview/product/quickview/id/' . $_item->getId()) ?>" title="<?php echo $block->escapeHtml(__('Quick view')); ?>" class="ajax diamond tooltip-hover" data-placement="top" data-original-title="<?php echo ('Quick view') ?>">
                                                <i class="fa fa-compress"></i>
                                            </a>
                                        </div>
                                    </li>
                                    <?php endif; ?>
                                    <?php if( $showCompare ): ?>
                                    <?php
                                        $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');
                                    ?>
                                    <li>
                                        <a href="#" class="action button tocompare" title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>" aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>" data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_item); ?>' role="button">
                                            <i class="fa fa-sliders"></i>
                                        </a>
                                    </li>
                                    <?php endif; ?>
                                    <?php if( $showWishlist ): ?>
                                        <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()): ?>
                                        <li>
                                            <a href="#"
                                               class="action button towishlist"
                                               title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                               aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                               data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_item); ?>'
                                               data-action="add-to-wishlist"
                                               role="button">
                                                <i class="fa fa-heart-o"></i>
                                            </a>
                                        </li>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                </ul>
                                <?php endif; ?>
                            </div>
                        </div>
                        <?php if ( $_item->getFinalPrice() < $_item->getPrice() ): ?>
                            <span class="onsale">
                                <span class="sale-bg"></span>
                                <span class="sale-text"><?php echo __('Sale') ?></span>
                            </span>
                        <?php endif; ?>
                        <?php $todayDate = time(); 
                            $timeStartNew = strtotime($_item->getData('news_from_date'));
                            $timeEndNew = strtotime($_item->getData('news_to_date')); ?>
                        <?php if ( $timeEndNew >= $todayDate && $timeStartNew <= $todayDate): ?>
                            <span class="newlabel">
                                <span><?php echo __('New') ?></span>
                            </span>
                        <?php endif; ?>
                    </div>
				</div>
                    <div class="product-info">
						<h3 class="product-name"><a class="product-item-link" title="<?php echo $block->escapeHtml($_item->getName()) ?>" href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>">
						<?php echo $block->escapeHtml($_item->getName()) ?></a>
						</h3>
						<?php /* @escapeNotVerified */ echo $block->getProductPrice($_item); ?>

                        <?php if ($templateType): ?>
                            <?php echo $block->getReviewsSummaryHtml($_item, $templateType) ?>
                        <?php endif; ?>
                        <?php if ($showCart): ?>
                            <div class="actions-primary">
                                <?php if ($_item->isSaleable()): ?>
                                    <?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)): ?>
                                        <button class="action tocart primary" data-mage-init='{"redirectUrl": {"url": "<?php /* @escapeNotVerified */ echo $block->getAddToCartUrl($_item) ?>"}}' type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
                                            <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                        </button>
                                    <?php else: ?>
                                        <?php $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
                                        $postData = $postDataHelper->getPostData($block->getAddToCartUrl($_item), ['product' => $_item->getEntityId()])
                                        ?>
                                        <button class="btn btn-add-to-cart"
                                                data-post='<?php /* @escapeNotVerified */ echo $postData; ?>'
                                                type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
                                            <i class="fa fa-shopping-basket">&nbsp;</i>
                                        </button>
                                    <?php endif; ?>
                                <?php else: ?>
                                    <?php if ($_item->getIsSalable()): ?>
                                        <div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
                                    <?php else: ?>
                                        <div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
                                    <?php endif; ?>
                                <?php endif; ?>
                            </div>
                        <?php endif; ?>
                    </div>
                    <?php echo($iterator == count($items)+1) ? '</li>' : '' ?>
                <?php endforeach ?>
            </ol>
			</div>
        </div>
    </div>
</div>
<?php endif;?>
<script type="text/javascript">
	require([
		'jquery',
		'mage/mage',
		'rokanthemes/owl'
	], function ($) {
		'use strict';

		jQuery("<?php echo $blockOwlClass; ?>").owlCarousel({
			lazyLoad: true,
			autoPlay : false,
			items : 4,
			itemsDesktop : [1199,3],
			itemsDesktopSmall : [980,2],
			itemsTablet: [768,2],
			itemsMobile : [479,1],
			slideSpeed : 500,
			paginationSpeed : 500,
			rewindSpeed : 500,
			navigation : true,
			stopOnHover : true,
			pagination :false,
			scrollPerPage:true,
		});
	});
</script>