<?php $_item = $block->getItem(); ?>
<tbody class="cart item">
    <tr class="item-info">
        <td data-th="<?= $block->escapeHtml(__('Item')); ?>" class="col item">
            <?php if ($block->hasProductUrl()) :?>
                <a href="<?= $block->getProductUrl() ?>"
                    title="<?= $block->escapeHtml($block->getProductName()) ?>"
                    tabindex="-1"
                    class="product-item-photo">
            <?php else :?>
                <span class="product-item-photo">
            <?php endif;?>

            <?= $block->getImage($block->getProductForThumbnail(), 'cart_page_product_thumbnail')->toHtml(); ?>

            <?php if ($block->hasProductUrl()) :?>
                </a>
            <?php else : ?>
                </span>
            <?php endif; ?>

            <div class="product-item-details">
                <strong class="product-item-name">
                    <?php if ($block->hasProductUrl()) :?>
                        <a href="<?= $block->getProductUrl() ?>"
                        ><?= $block->escapeHtml($block->getProductName()) ?></a>
                    <?php else : ?>
                        <?= $block->escapeHtml($block->getProductName()) ?>
                    <?php endif; ?>
                </strong>

                <?php if ($_options = $block->getOptionList()) :?>
                    <dl class="item-options">
                        <?php foreach ($_options as $_option) : ?>
                            <?php $_formatedOptionValue = $block->getFormatedOptionValue($_option) ?>
                            <dt><?= $block->escapeHtml($_option['label']) ?></dt>
                            <dd>
                                <?php if (isset($_formatedOptionValue['full_view'])) : ?>
                                    <?= $_formatedOptionValue['full_view'] ?>
                                <?php else : ?>
                                    <?= $_formatedOptionValue['value'] ?>
                                <?php endif; ?>
                            </dd>
                        <?php endforeach; ?>
                    </dl>
                <?php endif;?>

                <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
                <?php if ($addInfoBlock) : ?>
                    <?= $addInfoBlock->setItem($_item)->toHtml() ?>
                <?php endif;?>
            </div>
        </td>

        <td class="col price" data-th="<?= $block->escapeHtml(__('Price')); ?>">
            <?= $block->getUnitPriceHtml($_item); ?>
        </td>

        <td class="col qty" data-th="<?= $block->escapeHtml(__('Qty')); ?>">
            <?= $block->getQty() ?>
        </td>

        <td class="col subtotal" data-th="<?= $block->escapeHtml(__('Subtotal'));?>">
            <?= $block->getRowTotalHtml($_item); ?>
        </td>
    </tr>
</tbody>