<?php
$_brandCollection       = $block->getBrandCollection();
$_helper                = $this->helper('Rokanthemes\Brand\Helper\Data');
$title                  = $this->getConfig('widget_title');
$subtitle                  = $this->getConfig('widget_sub_title');
$show_brand_name        = $this->getConfig('show_brand_name');

$blockId                = rand().time();
$number_item_per_column    = (int)$this->getConfig('number_item_per_column');
if($number_item_per_column == '' || $number_item_per_column == 0)
	$number_item_per_column = 1;

$default_items          = $this->getConfig('default_items');
$addition_class         = $this->getConfig('addition_class');
$mobile_items           = (int)$this->getConfig('mobile_items',1);
$tablet_small_items     = (int)$this->getConfig('tablet_small_items',2);
$tablet_items           = (int)$this->getConfig('tablet_items',3);
$portrait_items         = (int)$this->getConfig('portrait_items',4);
$large_items            = (int)$this->getConfig('large_items',5);
$dots                   = $this->getConfig('dots');
$nav                    = $this->getConfig('nav');
$nav_prev               = $this->getConfig('nav_prev');
$nav_next               = $this->getConfig('nav_next');
$loop                   = $this->getConfig('loop');
$autoplay               = $this->getConfig('autoplay');
$autoplay_timeout       = (int)$this->getConfig('autoplay_timeout',3000);
$autoplay_pauseonhover  = (int)$this->getConfig('autoplay_pauseonhover');
$auto_play              = $this->getConfig('auto_play');
$speed                  = $this->getConfig('speed');
$rtl                    = $this->getConfig('rtl');

$html = '';
$cmsblock = $this->getConfig('cmsblock');
$pretext_html = $this->getConfig('pretext_html');
if($pretext_html){
	$html = base64_decode($pretext_html);
}elseif($cmsblock!=''){
	$html = $this->getCmsBlockModel()->load($cmsblock)->getContent();
}
$html = $_helper->filter($html);
?>
<?php if ( $_brandCollection->count() ){ ?>
<?php
$_collection = [];
$i = $x = 0;
$total  = $_brandCollection->count();
$column = 8;
if($total%$number_item_per_column == 0){
	$column = $total/$number_item_per_column;
}else{
	$column = floor($total/$number_item_per_column)+1;
}
if($column<$default_items) $column = $default_items;
$i = $x = 0;
foreach ($_brandCollection as $_brand) {
	if($i<$column){
		$i++;
	}else{
		$i = 1;
		$x++;
	}
	$_collection[$i][$x] = $_brand;
} 
?>
<div class="block widget rokan-widget brand-widget <?php echo $addition_class?$addition_class:'' ?>">
	<?php if($title){ ?>
	<div class="block-title"><strong><?php echo $title ?></strong></div>
	<?php } ?>
	<?php if($subtitle){ ?>
	<div class="block-sub-title"><strong><?php echo $subtitle ?></strong></div>
	<?php } ?>
	<?php if($html!=''){ ?>
	<div class="pretext-html"><?php echo $html ?></div>
	<?php } ?>
	<div class="block-content brandowl-play">
		<ul id="rokan-carousel<?php echo $blockId ?>" class="owl-carousel rokan-carousel<?php echo $blockId ?>" data-rtl="<?php echo $rtl?"true":"false" ?>" data-loop="<?php echo $loop?"true":"false" ?>" data-nav="false" data-dot="<?php echo $dots?"true":"false" ?>" data-autoplay="<?php echo $autoplay?"true":"false" ?>" data-autoplay-timeout="<?php echo $autoplay_timeout ?>" data-pauonhover="<?php echo $autoplay_pauseonhover?"true":"false" ?>" data-mobile-items="<?php echo (int)$mobile_items ?>" data-tablet-small-items="<?php echo (int)$tablet_small_items ?>" data-tablet-items="<?php echo (int)$tablet_items ?>" data-portrait-items="<?php echo (int)$portrait_items ?>" data-large-items="<?php echo (int)$default_items ?>" data-large-max-items="<?php echo (int)$large_items ?>" >
			<?php foreach ($_collection as $_brandCollection) { ?>
			<li class="item">
				<?php foreach ($_brandCollection as $_brand) { ?>
				<div class="brand-item">
					<div class="brand-image"><a href="<?php echo $_brand->getUrl(); ?>" title="<?php echo $_brand->getName(); ?>"><img src="<?php echo $_brand->getThumbnailUrl(); ?>" alt="<?php echo $_brand->getName(); ?>"/></a></div>
					<?php if($show_brand_name){ ?>
					<div class="brand-name"><a href="<?php echo $_brand->getUrl(); ?>" title="<?php echo $_brand->getName(); ?>"><?php echo $_brand->getName() ?></a></div>
					<?php } ?>
				</div>
				<?php } ?>
			</li>
			<?php } ?>
		</ul>
		<?php if($nav){ ?>
		<a href="javascript:void(0);" class="owl-left"><?php echo $nav_prev?$nav_prev:'Prev'; ?></a>
		<a href="javascript:void(0);" class="owl-right"><?php echo $nav_next?$nav_next:'Next'; ?></a>
		<?php } ?>
	</div>
</div>
<?php } ?>
<script type="text/javascript">
require(['jquery','rokanthemes/owl'], function ($) {
	if(jQuery(".brandowl-play").length > 0 ) {
		var owlItems = [];
		jQuery(".brandowl-play").each( function(){
			var owlCarousel = jQuery(this).find(".owl-carousel");
			if(!owlItems[jQuery(owlCarousel).attr("id")]){
				var config = [];
				owlItems[jQuery(owlCarousel).attr("id")] = true;
				if(typeof(jQuery(owlCarousel).data('nav'))!='underfined'){
					config['nav'] = jQuery(owlCarousel).data('nav');
				}
				if(typeof(jQuery(owlCarousel).data('dot'))!='underfined'){
					config['dot'] = jQuery(owlCarousel).data('dot');
				}

				if(typeof(jQuery(owlCarousel).data('autoplay'))!='underfined'){
					config['autoPlay'] = jQuery(owlCarousel).data('autoplay');
				}
				
				if(jQuery(owlCarousel).data('autoplay-timeout')){
					config['autoplayTimeout'] = jQuery(owlCarousel).data('autoplay-timeout');
				}
				if(typeof(jQuery(owlCarousel).data('autoplay-pauonhover'))!='underfined'){
					config['autoplayHoverPause'] = jQuery(owlCarousel).data('autoplay-pauonhover');
				}
				if(typeof(jQuery(owlCarousel).data('rtl'))!='underfined'){
					config['rtl'] = jQuery(owlCarousel).data('rtl');
				}
				if(typeof(jQuery(owlCarousel).data('loop'))!='underfined'){
					config['loop'] = jQuery(owlCarousel).data('loop');
				}
				config['navText'] = [ 'prev', 'next' ];
				if(jQuery(owlCarousel).data("nav-text-owlpre")){
					config['navText'] = [ jQuery(owlCarousel).data("nav-text-owlpre"), 'next' ];
				}
				if(jQuery(owlCarousel).data("nav-text-owlnext")){
					config['navText'] = [ 'pre', jQuery(owlCarousel).data("nav-text-owlnext") ];
				}
				if(jQuery(owlCarousel).data("nav-text-owlpre") && jQuery(owlCarousel).data("nav-text-owlnext")){
					config['navText'] = [ jQuery(owlCarousel).data("nav-text-owlpre"), jQuery(owlCarousel).data("nav-text-owlnext") ];   
				}
				var mobile_items = 1;
				if(jQuery(owlCarousel).data('mobile-items')){
					mobile_items = jQuery(owlCarousel).data('mobile-items');
				}
				var tablet_small_items = 1;
				if(jQuery(owlCarousel).data('tablet-small-items')){
					tablet_small_items = jQuery(owlCarousel).data('tablet-small-items');
				}
				var tablet_items = 2;
				if(jQuery(owlCarousel).data('tablet-items')){
					tablet_items = jQuery(owlCarousel).data('tablet-items');
				}
				var portrait_items = 2;
				if(jQuery(owlCarousel).data('portrait-items')){
					portrait_items = jQuery(owlCarousel).data('portrait-items');
				}
				var large_items = 4;
				if(jQuery(owlCarousel).data('large-items')){
					large_items = jQuery(owlCarousel).data('large-items');
				}
				var large_max_items = 5;
				if(jQuery(owlCarousel).data('large-max-items')){
					large_max_items = jQuery(owlCarousel).data('large-max-items');
					config['items'] = jQuery(owlCarousel).data('large-max-items');
				}
				config['itemsDesktop'] = [1199,5];
				config['itemsDesktopSmall'] = [980,4];
				config['itemsTablet'] = [768,2];
				config['itemsMobile'] = [479,1];
				
				jQuery(owlCarousel).owlCarousel(config);
				jQuery('.owl-left',jQuery(owlCarousel).parent()).click(function(){
					owlCarousel.trigger('prev.owl.carousel');
					return false;
				});
				jQuery('.owl-right',jQuery(owlCarousel).parent()).click(function(){
					owlCarousel.trigger('next.owl.carousel');
					return false;
				});
				// var id = jQuery(owlCarousel).attr("id");
				// if(jQuery("#" + id + " .brand-item").height){
					// var height = 0;
					// jQuery("#" + id + " .brand-item").each(function(){
						// if(jQuery(this).height()>height){
							// height = jQuery(this).height();
						// }
					// });
					// if(height>0){
						// jQuery("#" + id + " .brand-item").css({"height":height+"px"});
					// }
				// };
			};
		});
	}
});
</script>