<?php

$subscriptions = $this->getSubscriptions();
$customerCards = $this->getCustomerCards();

if (empty($subscriptions)): ?>
<div class="message info empty">
  <span><?php echo __("You do not have any subscriptions yet."); ?></span>
</div>
<?php else: ?>
  <div class="table-wrapper stripe-subscriptions">
    <table class="data table table-order-items history" id="my-orders-table">
      <caption class="table-caption"><?php echo __("Subscriptions"); ?></caption>
      <thead>
        <tr>
          <th scope="col" class="col order"><?php echo __("Order #"); ?></th>
          <th scope="col" class="col id"><?php echo __("Subscription"); ?></th>
          <th scope="col" class="col delivery"><?php echo __("Delivery Every"); ?></th>
          <th scope="col" class="col billed"><?php echo __("Last Billed"); ?></th>
          <th scope="col" class="col total"><?php echo __("Status"); ?></th>
          <th scope="col" class="col status"><?php echo __("Actions"); ?></th>
        </tr>
      </thead>
      <tbody>
  <?php foreach ($subscriptions as $subscription): ?>
        <tr>
          <td data-th="Order #" class="col order">
            <a href="viewOrder/<?php echo $subscription->metadata["Order #"]; ?>">
              <?php echo $subscription->metadata["Order #"]; ?>
            </a>
          </td>
          <td data-th="<?php echo __("Subscription"); ?>" class="col id">
            <a href="javascript:void(0)" class="subscription-name" onclick="stripe.toggleSubscription('.<?php echo $subscription->id; ?>', false);">
              <?php echo $this->formatSubscriptionName($subscription); ?>
            </a>
            <?php if ($this->hasEditableContent($subscription)): ?>
              <div class="<?php echo $subscription->id; ?> shipping-method stripe-subscription-edit">
                <div class="static section">
                  <div class="details">
                    <b><?php echo __("Shipping Address"); ?></b><br>
                    <?php echo implode("<br>", $this->getFormatedShippingLines($subscription)); ?>
                  </div>
                  <div class="actions">
                    <button onclick="stripe.editSubscription('.<?php echo $subscription->id; ?>.shipping-method')" class="action edit">Edit</button> or
                    <a href="javascript:void(0)" onclick="stripe.toggleSubscription('.<?php echo $subscription->id; ?>')" class="action close"><?php echo __("Close"); ?></a>
                  </div>
                </div>
                <div class="mutable section">
                  <form action="edit/<?php echo $subscription->id; ?>" method="POST">
                    <div class="details">
                      <b><?php echo __("Shipping Address"); ?></b><br>
                      <?php foreach ($this->editableContent() as $key): ?>
                        <input type="text"
                          value="<?php echo $subscription->metadata[$key]; ?>"
                          name="data[<?php echo $key; ?>]"
                          placeholder="<?php echo $key; ?>"
                          class="input-text"><br>
                      <?php endforeach; ?>
                    </div>
                    <div class="actions">
                      <button type="submit"><?php echo __("Save"); ?></button> <?php echo __("or"); ?>
                      <a href="javascript:void(0)" onclick="stripe.cancelEditSubscription('.<?php echo $subscription->id; ?>.shipping-method')"><?php echo __("Cancel"); ?></a>
                    </div>
                  </form>
                </div>
              </div>
            <?php endif; ?>
            <div class="<?php echo $subscription->id; ?> payment-method stripe-subscription-edit">
              <div class="static section">
                <b><?php echo __("Payment Method"); ?></b><br>
                <div class="details stripe-payments">
                  <?php $card = $block->getSubscriptionCard($subscription); ?>
                  <?php if ($card): ?>
                    <span class="type <?php echo $card->brand; ?>">
                      <?php echo $block->helper->cardType($card->brand); ?>
                    </span>
                    <span class="last4">
                      **** <?php echo $card->last4; ?>
                    </span>
                    <span class="exp">
                      <?php echo $card->exp_month; ?>/<?php echo $card->exp_year; ?>
                    </span>
                  <?php else: ?>
                    <?php echo __("None"); ?>
                  <?php endif; ?>
                </div>
                <div class="actions">
                  <button onclick="stripe.editSubscription('.<?php echo $subscription->id; ?>.payment-method')" class="action edit">Edit</button> or
                  <a href="javascript:void(0)" onclick="stripe.toggleSubscription('.<?php echo $subscription->id; ?>')" class="action close"><?php echo __("Close"); ?></a>
                </div>
              </div>
              <div class="mutable section">
                <b><?php echo __("Payment Method"); ?></b><br>
                <form action="changeCard/<?php echo $subscription->id; ?>" method="POST">
                  <div class="details">
                    <?php $cardId = $block->getSubscriptionCardId($subscription); ?>
                    <?php foreach ($customerCards as $card): ?>
                      <div class="subscription-card stripe-payments">
                        <input type="radio" id="<?php echo $subscription->id . "_" . $card->id; ?>" name="subscription_card" value="<?php echo $card->id; ?>"
                          <?php if ($cardId == $card->id) echo "checked"; ?>>
                        <label for="<?php echo $subscription->id . "_" . $card->id; ?>">
                          <span class="type <?php echo $card->brand; ?>">
                            <?php echo $block->helper->cardType($card->brand); ?>
                          </span>
                          <span class="last4">
                            **** <?php echo $card->last4; ?>
                          </span>
                          <span class="exp">
                            <?php echo $card->exp_month; ?>/<?php echo $card->exp_year; ?>
                          </span>
                        </label>
                      </div>
                    <?php endforeach; ?>
                    <div class="subscription-card add-new">
                      <a href="<?php echo $this->getUrl('stripe/customer/cards'); ?>"><?php echo __("Add a new card"); ?></a>
                    </div>
                  </div>
                  <div class="actions">
                    <button type="submit"><?php echo __("Save"); ?></button> <?php echo __("or"); ?>
                    <a href="javascript:void(0)" onclick="stripe.cancelEditSubscription('.<?php echo $subscription->id; ?>.payment-method')"><?php echo __("Cancel"); ?></a>
                  </div>
                </form>
              </div>
            </div>
          </td>
          <td data-th="<?php echo __("Delivery Every"); ?>" class="col delivery">
            <?php echo $this->formatDelivery($subscription); ?>
          </td>
          <td data-th="<?php echo __("Last Billed"); ?>" class="col billed">
            <?php echo $this->formatLastBilled($subscription); ?>
          </td>
          <td data-th="Status" class="col status">
          <?php echo $this->getStatus($subscription); ?>
          </td>
          <td data-th="Actions" class="col actions">
            <a href="cancel/<?php echo $subscription->id; ?>" class="action cancel"
              onclick="return confirm('<?php echo __("Are you sure you want to cancel this subscription?"); ?>');">
              <span><?php echo __("Cancel"); ?></span>
            </a>
            <a href="javascript:void(0)" onclick="stripe.toggleSubscription('.<?php echo $subscription->id; ?>', true);" class="action edit">
              <span><?php echo __("Edit"); ?></span>
            </a>
          </td>
        </tr>
  <?php endforeach; ?>
      </tbody>
    </table>
  </div>
<?php endif;
