<?php 
	$data = $block->getConfig();
?>
<?php if (isset($data['general']['enable_preloaded']) && $data['general']['enable_preloaded'] == 1){ ?>
<ul class="loader">
  <li class="center"></li>
  <li class="item item-1"></li>
  <li class="item item-2"></li>
  <li class="item item-3"></li>
  <li class="item item-4"></li>
  <li class="item item-5"></li>
  <li class="item item-6"></li>
  <li class="item item-7"></li>
  <li class="item item-8"></li>
</ul>
<script type="text/javascript">
require([
		'jquery'
	], function ($) {
		'use strict';
		$(window).load(function() {
			$('.loader').delay(500).fadeOut('slow');
		});
		$( document ).ready(function() {
			var myVarloader = setInterval(function(){ setLoaderTime() }, 2000);
			function setLoaderTime() {
				$('.loader').delay(500).fadeOut('slow');
				clearInterval(myVarloader);
			}
		});
});
</script>
<?php } ?>