<?php

/**

 * Copyright © Magento, Inc. All rights reserved.

 * See COPYING.txt for license details.

 */



/** @var \Magento\Catalog\Block\Product\View\Details $block */

?>



<?php

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();

$_product = $objectManager->get('Magento\Framework\Registry')->registry('current_product');

$attribute_set_id = 4;

if($_product){

	$attribute_set_id = $_product->getAttributeSetId();

}

?>



<?php 
if ($detailedInfoGroup = $block->getGroupChildNames('detailed_info', 'getChildHtml')) :
//if ($detailedInfoGroup = $block->getGroupSortedChildNames('detailed_info', 'getChildHtml')) :?>

    <div class="product info detailed">

        <?php $layout = $block->getLayout(); ?>

        <div class="product data items" data-mage-init='{"tabs":{"openedState":"active"}}'>

            <?php foreach ($detailedInfoGroup as $name) :?>

                <?php

                $html = $layout->renderElement($name);

                if (!trim($html)) {

                    continue;

                }

                $alias = $layout->getElementAlias($name);

                $label = $block->getChildData($alias, 'title');

                

                if($attribute_set_id != 9 || ($attribute_set_id == 9 && $alias != 'reviews')){ ?>

	                <div class="data item title"

	                     data-role="collapsible" id="tab-label-<?= $block->escapeHtmlAttr($alias) ?>">

	                    <a class="data switch"

	                       tabindex="-1"

	                       data-toggle="trigger"

	                       href="#<?= $block->escapeUrl($alias) ?>"

	                       id="tab-label-<?= $block->escapeHtmlAttr($alias) ?>-title">

	                        <?= /* @noEscape */ $label ?>

	                    </a>

	                </div>

	                <div class="data item content"

	                     aria-labelledby="tab-label-<?= $block->escapeHtmlAttr($alias) ?>-title" id="<?= $block->escapeHtmlAttr($alias) ?>" data-role="content">

	                    <?= /* @noEscape */ $html ?>

	                </div>

				<?php } ?>

            <?php endforeach;?>

        </div>

    </div>

<?php endif; ?>

