<script type='text/javascript'>
    require([
        'Rokanthemes_OpCheckout/js/model/addressFieldManager'
    ], function(addressFieldManager) {
        addressFieldManager.init(<?php echo $this->helper('Rokanthemes\OpCheckout\Helper\Config')->getAddressFieldsJsonConfig();?>);
    })
</script>
<ol class="one-step-checkout opcheckout-index-index three-columns-new-osc clearfix">
    <li id="checkout" data-bind="scope:'checkout'" class="checkout-container">
        <div id="checkout-loader" data-role="checkout-loader" class="loading-mask show" data-mage-init='{"checkoutLoader": {}}'>
            <div class="loader">
                <img src="<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('images/loader-1.gif'); ?>"
                     alt="<?php /* @escapeNotVerified */ echo __('Loading...'); ?>"
                     style="position: absolute;">
            </div>
        </div>
        <!-- ko template: getTemplate() --><!-- /ko -->
        <script type="text/x-magento-init">
            {
                "#checkout": {
                    "Magento_Ui/js/core/app": <?php /* @escapeNotVerified */ echo $block->getJsLayout();?>
                }
            }
        </script>
        <script>
            window.checkoutConfig = <?php echo \Zend_Json::encode($block->getCheckoutConfig()); ?>;
            window.isCustomerLoggedIn = window.checkoutConfig.isCustomerLoggedIn;
            window.customerData = window.checkoutConfig.customerData;
        </script>
        <script>
            require([
                'mage/url',
                'Magento_Ui/js/block-loader'
            ], function(url, blockLoader) {
                blockLoader("<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('images/loader-1.gif'); ?>");
                return url.setBaseUrl('<?php /* @escapeNotVerified */ echo $block->getBaseUrl();?>');
            })
        </script>
    </li>
</ol>